#!/bin/sh /etc/rc.common

NAME=ciadpi
PROG=/usr/bin/ciadpi
PORT=10080

START=99
STOP=10

USE_PROCD=1

CIADPI_ARGS="-Ku -a1 -An -o1 -At,r,s -d1 -p $PORT --transparent"

MARK=0x00000004

add_nft_rules() {
    del_nft_rules
    nft add rule inet fw4 dstnat_lan iifname "br-lan" meta l4proto { tcp, udp } meta mark $MARK redirect to :$PORT
}

del_nft_rules() {
    local RULE_HANDLE=$(nft -a list chain inet fw4 dstnat_lan | grep "meta l4proto { tcp, udp } meta mark $MARK redirect to :$PORT" | awk '{print $NF}')
    if [ -n "$RULE_HANDLE" ]; then
        nft delete rule inet fw4 dstnat_lan handle "$RULE_HANDLE"
    fi
}

start_service() {
    add_nft_rules

    procd_open_instance "$NAME"
    procd_set_param command "$PROG" $CIADPI_ARGS
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    stop
    start
}

stop_service() {
    del_nft_rules
}
