#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c '
        DNS="external"
        INTERVAL=86400
        . /lib/functions/network.sh

        while :; do
            network_get_ipaddr IP wan && [ -n "$IP" ] && {
                uci set dhcp.external=domain
                uci set dhcp.external.name="$DNS"
                uci set dhcp.external.ip="$IP"
                uci commit dhcp
                /etc/init.d/dnsmasq restart

                logger -t external-ip "Updated $DNS -> $IP"
            }
            sleep $INTERVAL
        done
    '
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
