#!/bin/sh /etc/rc.common

START=99

start() {
    OUTPUT_FILE="/tmp/dnsmasq.d/domains.lst"
    > "$OUTPUT_FILE"

    DOMAINS="
        https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-dnsmasq-nfset.lst
        https://raw.githubusercontent.com/labi-le/domains.lst/main/d.lst
    "

    EXCLUDED_DOMAINS="
        youtube.com
        ytimg.com
        yting.com
        ggpht.com
        googlevideo.com
        youtubekids.com
        youtu.be
        youtube-nocookie.com
        wide-youtube.l.google.com
        ytimg.l.google.com
        youtubei.googleapis.com
        youtubeembeddedplayer.googleapis.com
        youtube-ui.l.google.com
        yt-video-upload.l.google.com
        jnn-pa.googleapis.com
        returnyoutubedislikeapi.com
    "

    count=0
    while true; do
        if curl -m 3 github.com; then
            for DOMAIN in $DOMAINS; do
                echo "Processing $DOMAIN"
                curl -f "$DOMAIN" | while read line; do
                    # Check if the line is in the excluded domains list
                    excluded=0
                    for EXCLUDED_DOMAIN in $EXCLUDED_DOMAINS; do
                        if [[ "$line" == *"$EXCLUDED_DOMAIN"* ]]; then
                            excluded=1
                            break
                        fi
                    done
                    if [ "$excluded" -eq 0 ]; then
                        echo "$line" >> "$OUTPUT_FILE"
                    fi
                done
            done
            break
        else
            echo "GitHub is not available. Check the internet availability [$count]"
            count=$((count+1))
        fi
    done

    if dnsmasq --conf-file=$OUTPUT_FILE --test 2>&1 | grep -q "syntax check OK"; then
        /etc/init.d/dnsmasq restart
    fi
}
