mode: rule
allow-lan: true
bind-address: "*"
log-level: debug
ipv6: false
tproxy-port: 12342

iptables:
  inbound-interface: br-lan

proxies:
  - name: VPN
    type: direct
    udp: true
    interface-name: awg2

  - name: WARP-AWG1
    type: direct
    udp: true
    interface-name: awg1

  - name: WARP-AWG0
    type: direct
    udp: true
    interface-name: awg0

dns:
  enable: true
  listen: 0.0.0.0:12344
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.1.0/24
  store-fake-ip: true
  fake-ip-filter-mode: rule
  fake-ip-filter:
    - DOMAIN-SUFFIX,lan,real-ip
    - DOMAIN-SUFFIX,local,real-ip
    - RULE-SET,vpn,fake-ip
    - RULE-SET,warp,fake-ip
    - MATCH,real-ip
  nameserver:
    - 127.0.0.1:5453

proxy-providers:
  mifa:
    type: http
    url: "http://192.168.1.2:7008?subscription_url=https://mifa.world/vless&countries=FI,EE,LV,LT,SE,PL,DE,NL"
    path: ./providers/mifa.yaml
    interval: 3600
    health-check:
      enable: true
      url: "https://aistudio.google.com/"
      interval: 90
      timeout: 2000
      lazy: false
      expected-status: 302

proxy-groups:
  - name: WARP
    type: fallback
    proxies:
      - WARP-AWG1
      - WARP-AWG0
    url: "https://www.gstatic.com/generate_204"
    interval: 900
    tolerance: 150
    expected-status: 204

  - name: VPN-MIFA-AUTO
    type: url-test
    use:
      - mifa
    url: "https://aistudio.google.com/"
    interval: 90
    timeout: 2000
    tolerance: 300
    lazy: false
    expected-status: 302
    max-failed-times: 1
    filter: "(?i)(Finland|Estonia|Latvia|Lithuania|Sweden|Poland|Germany|Netherlands)"
    exclude-filter: "(?i)(Russia|test|demo|expired|dead|trial)"
    empty-fallback: REJECT

  - name: VPN-PREFERRED
    type: fallback
    proxies:
      - VPN-MIFA-AUTO
#      - VPN
    url: "https://aistudio.google.com/"
    interval: 0
    lazy: false
    timeout: 2000
    expected-status: 302
    max-failed-times: 1

rule-providers:
  vpn:
    type: file
    path: ./rules/vpn.txt
    behavior: classical
    format: text

  warp:
    type: file
    path: ./rules/warp.txt
    behavior: classical
    format: text

rules:
  - RULE-SET,vpn,VPN-PREFERRED
  - RULE-SET,warp,WARP
  - MATCH,DIRECT
