mode: rule
allow-lan: true
bind-address: "*"
log-level: debug
ipv6: false
tproxy-port: 12342

iptables:
  inbound-interface: br-lan

proxies:
  - name: VPN
    type: direct
    udp: true
    interface-name: awg2

  - name: WARP-AWG1
    type: direct
    udp: true
    interface-name: awg1

  - name: WARP-AWG0
    type: direct
    udp: true
    interface-name: awg0

dns:
  enable: true
  listen: 0.0.0.0:12344
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.1.0/24
  store-fake-ip: true
  fake-ip-filter-mode: rule
  fake-ip-filter:
    - DOMAIN-SUFFIX,lan,real-ip
    - DOMAIN-SUFFIX,local,real-ip
    - RULE-SET,vpn,fake-ip
    - RULE-SET,warp,fake-ip
    - MATCH,real-ip
  nameserver:
    - 127.0.0.1:5453

proxy-providers:
  goida:
    type: http
    url: "https://raw.githubusercontent.com/AvenCores/goida-vpn-configs/refs/heads/main/githubmirror/25.txt"
    path: ./providers/goida.yaml
    interval: 3600
    health-check:
      enable: true
      url: "http://fast.com"
      interval: 300

  vlessforu:
    type: http
    url: "https://raw.githubusercontent.com/bobrinaw/vlessforu/refs/heads/main/working_configs.txt"
    path: ./providers/vlessforu.yaml
    interval: 3600
    health-check:
      enable: true
      url: "http://fast.com"
      interval: 300

  mos-eu:
    type: http
    url: "https://hub.mos.ru/zieng2/wl/raw/main/list_universal.txt"
    path: ./providers/mos-eu.yaml
    interval: 3600
    health-check:
      enable: true
      url: "http://fast.com"
      interval: 300

  mos-purple:
    type: http
    url: "https://hub.mos.ru/panosenk/sukasubs/-/raw/main/purple.txt"
    path: ./providers/mos-purple.yaml
    interval: 3600
    health-check:
      enable: true
      url: "http://fast.com"
      interval: 300

proxy-groups:
  - name: WARP
    type: fallback
    proxies:
      - WARP-AWG1
      - WARP-AWG0
    url: "https://gstatic.com/generate_204"
    interval: 900
    tolerance: 150

  - name: VPN-SUB-GOIDA
    type: fallback
    use:
      - goida
    url: "http://fast.com"
    interval: 300
    tolerance: 150
    filter: "(?i)(🇩🇪|🇫🇷|🇫🇮|🇱🇻|🇳🇱|🇷🇴|🇮🇹)"
    empty-fallback: REJECT

  - name: VPN-SUB-VLESS
    type: fallback
    use:
      - vlessforu
    url: "http://fast.com"
    interval: 300
    tolerance: 150
    empty-fallback: REJECT

  - name: VPN-SUB-EU
    type: fallback
    use:
      - mos-eu
    url: "http://fast.com"
    interval: 300
    tolerance: 150
    filter: "(?i)(Estonia|Finland|Lithuania|Latvia|Poland|Germany|Netherlands|Czechia|Sweden|Norway|Denmark)"
    empty-fallback: REJECT

  - name: VPN-SUB-PURPLE
    type: fallback
    use:
      - mos-purple
    url: "http://fast.com"
    interval: 300
    tolerance: 150
    filter: "(?i)(purple|💜)"
    empty-fallback: REJECT

  - name: VPN-PREFERRED
    type: fallback
    proxies:
      - VPN
      - VPN-SUB-PURPLE
      - VPN-SUB-GOIDA
      - VPN-SUB-VLESS
      - VPN-SUB-EU
    url: "http://fast.com"
    interval: 300
    tolerance: 150

rule-providers:
  vpn:
    type: file
    path: ./rules/vpn.txt
    behavior: classical
    format: text

  warp:
    type: file
    path: ./rules/warp.txt
    behavior: classical
    format: text

rules:
  - RULE-SET,vpn,VPN-PREFERRED
  - RULE-SET,warp,WARP
  - MATCH,DIRECT
